/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

 // Habilita o gerenciamento de plugins para builds futuros
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

// Habilita repositórios convencionais para builds multiprojeto
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}



rootProject.name = "template-java"
include("app")
